import { ApertureButton } from "./ApertureLogo";

export function SiteHeader() {
  return (
    <header class="site-header">
      <div class="brand">
        <ApertureButton />
        <a href="/" aria-label="f.camera home">
          f.camera
        </a>
      </div>
      <nav class="profile-links" aria-label="Find me online">
        <a class="profile-link" href="https://fka.dev" target="_blank" rel="noopener noreferrer">
          fka.dev <span aria-hidden="true">↗</span>
        </a>
        <a
          class="profile-link"
          href="https://www.instagram.com/fkadev/"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Instagram @fkadev"
        >
          @fkadev <span aria-hidden="true">↗</span>
        </a>
      </nav>
    </header>
  );
}

function CameraKit() {
  return (
    <div class="intro-kit">
      <p class="kit-label">I shoot with</p>
      <ul class="kit-list">
        <li class="kit-item">
          <span class="kit-icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false">
              <path d="M8 6.5 9.5 4h5L16 6.5h3A2 2 0 0 1 21 8.5v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-10a2 2 0 0 1 2-2Z" />
              <circle cx="12" cy="13" r="4" />
              <path d="M17.5 9.5h.5" />
            </svg>
          </span>
          <span>Fujifilm X-S20</span>
        </li>
        <li class="kit-item">
          <span class="kit-icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false">
              <rect x="6.5" y="2.5" width="11" height="19" rx="2.5" />
              <path d="M10 5h4m-3 14h2" />
            </svg>
          </span>
          <span>iPhone camera</span>
        </li>
      </ul>
    </div>
  );
}

export function PersonalIntro() {
  return (
    <section class="personal-intro" aria-labelledby="intro-title">
      <div>
        <p class="intro-eyebrow">A little about me</p>
        <h1 id="intro-title">Hi, I’m Fatih.</h1>
        <p class="intro-copy">
          I work on{" "}
          <a href="https://spacefast.com" target="_blank" rel="noopener noreferrer">
            Spacefast
          </a>{" "}
          at{" "}
          <a href="https://automattic.com" target="_blank" rel="noopener noreferrer">
            Automattic
          </a>
          , the company behind WordPress.com. I also build{" "}
          <a href="https://prompts.chat" target="_blank" rel="noopener noreferrer">
            prompts.chat
          </a>{" "}
          as a personal project.
        </p>
        <p class="intro-note">All photos here are taken by people, not generated by AI.</p>
      </div>
      <CameraKit />
    </section>
  );
}

export function SiteFooter() {
  return (
    <footer class="site-footer">
      <div class="footer-about">
        <a href="https://fka.dev" target="_blank" rel="noopener noreferrer">
          Fatih Kadir Akın <span aria-hidden="true">↗</span>
        </a>
        <a href="https://www.instagram.com/fkadev/" target="_blank" rel="noopener noreferrer">
          Instagram · @fkadev <span aria-hidden="true">↗</span>
        </a>
      </div>
      <a href="https://spacefast.com" target="_blank" rel="noopener noreferrer">
        Made with Spacefast <span aria-hidden="true">↗</span>
      </a>
    </footer>
  );
}
